name: New Marketplace Publisher
description: Open a request to become a new publisher in the Adoptium Marketplace
title: "[Marketplace]: "
labels: ["marketplace", "publisher"]
assignees:
  - tellison
body:
  - type: markdown
    attributes:
      value: |
        This form is only for Publishers who wish to be included in the [Adoptium Marketplace](https://www.adoptium.net/TODO/marketplace.html).
        
        The criteria for being included in the Marketplace is [described on the Working Group website](https://www.adoptium.net/TODO/marketplace_criteria.html). Publishers are encouraged
        to read through material and engage with the Working Group before submitting a new request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Please confirm the following criteria have been met before continuing:
  - type: checkboxes
    id: working_group_member
    attributes:
      label: Adoptium Working Group Member
      description: |
        Marketplace Publishers must be a Participant, Enterprise or Strategic Member of the Adoptium Working Group.
        A list of eligible members, and information about joining the Working Group are [available on our website](https://adoptium.net/members.html).
        The Working Group will check with the Eclipse Foundation your membership is in place before your Publisher listing is approved.
      options:
        - label: Eligible Adoptium Working Group Member
          required: true
  - type: checkboxes
    id: publisher_agreement
    attributes:
      label: Adoptium Marketplace Publisher Agreement
      description: |
        To be listed in the marketplace you must conform to the [Adoptium Marketplace Publisher Agreement](https://www.adoptium.net/TODO/marketplace_agreement.html). [Contact the Eclipse Foundation](mailto:license@eclipse.org?subject=[adoptium]%20Adoptium%20Marketplace%20Publisher%20Agreement) to execute a publisher agreement. 
        The Working Group will check with the Eclipse Foundation this agreement is in place before your Publisher listing is approved.
      options:
        - label: Adoptium Marketplace Publisher Agreement executed
          required: true
  - type: input
    id: publisher_logo
    attributes:
      label: Publisher Logo
      description: |
        Provide a link to a logo that identifies you as a Publisher and your listings in the marketplace.
        The logo should be 400px x 400px for optimal rendering.
      placeholder: "https://www.example.com/logo.jpg"
    validations:
      required: true
  - type: input
    id: metadata_location
    attributes:
      label: Link to Product listing
      description: |
        Provide a link to your marketplace listing information.
      placeholder: "https://www.example.com/adoptium_marketplace_data.json"
    validations:
      required: true
  - type: input
    id: signature_location
    attributes:
      label: Link to Product listing signature
      description: |
        Provide a link to your detached base64-encoded marketplace listing information signature.
      placeholder: "https://www.example.com/adoptium_marketplace_data.json.sig"
    validations:
      required: true
  - type: textarea
    id: public_key
    attributes:
      label: Publisher public key
      description: |
        Provide the public key of the keypair used to sign the marketplace listing information.
      placeholder: Paste public key here
    validations:
      required: true
  - type: input
    id: post_download_page
    attributes:
      label: Post download page
      description: |
        Provide a link to a page that will be displayed after a user starts downloading a binary from the marketplace. This page may be used to thank the user, offer support offerings, and so on.
      placeholder: "https://www.example.com/adoptium_downloading.html"
    validations:
      required: false
